name: PR Build Check

# Triggers the workflow only when a Pull Request targets the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    if: ${{ github.actor != 'Sea-farer' }}
    name: Verify Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Environment Compilation
        run: docker compose build